spring:
  profiles:
    include:
      - comm
---
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
---
server:
  config:
    activate:
      on-profile: prod
  port: 8080
  error.include-message: always
  tomcat:
    max-swallow-size: -1
#  reactive:
#    session:
#      cookie:
#        domain: .profilehub.info
#        secure: true

logging:
  config:
    activate:
      on-profile: prod
  level:
    root: ERROR
---
server:
  config:
    activate:
      on-profile: local
  port: 7002
  error.include-message: always
  tomcat:
    max-swallow-size: -1
  host:
    userApi: http://localhost:7001

logging:
  config:
    activate:
      on-profile: local
  level:
    root: DEBUG

#    spring:
#      security:
#        oauth2:
#          client:
#            registration:
#              github:
#                clientId: github-client-id
#                clientSecret: github-client-secret
#              google:
#                client-id: google-client-id
#                client-secret: google-client-secret